// on the rocks
questionDeck1 = [];
// happy hour
questionDeck2 = [];
// last call
questionDeck3 = [];

questionsArray = [];
let reader = new FileReader();

reader.readAsText("./questions.txt");

function getQuestion() {
  loadQuestionDecks();
  deckSelect = document.getElementById("decks").value;
  if (deckSelect === "All") {
    questionsArray = questionDeck1.concat(questionDeck2.concat(questionDeck3));
  } else if (deckSelect === "On The Rocks") {
    questionsArray = questionDeck1;
  } else if (deckSelect === "Happy Hour") {
    questionsArray = questionDeck2;
  } else if (deckSelect === "Last Call") {
    questionsArray = questionDeck3;
  }
  numQuestions = questionsArray.length;
  questionText = document.getElementById("question");
  questionText.innerHTML =
    questionsArray[Math.floor(Math.random() * numQuestions)];
  console.log("ran function");
}

function loadQuestionDecks() {
  questionDeck1 = [
    "What animal am I most like? Describe how this species and I are similar.",
    "Do any of your friends not like me?",
    "What's a habit, compulsion, or relationship you wish you could quit?",
    "Have you ever stolen anything? What, and why? Do you still have it?",
    "Do your best (or worst) impersonation of me. I promise to clap appreciatively.",
    "What's something you've done to try and be cool?",
    "Describe the first time we met. What was your honest first impression of me?",
    "If I didn't have my current job, what do you see me doing?",
    "What's the worst thing you've ever had to do at work or school? How'd you handle it?",
    "What's something I do that you hate?",
    "Describe your first real kiss. Then describe your last kiss.",
    "Have you ever been fired? If so, what for? If not, why not?",
    "What movie title describes your last relationship?",
    "Describe your worst bathroom-related disaster.",
    "What's something you think people should appreciate more about you?",
    "What are your vices? Have they gotten better or worse over time?",
    "What's something you miss about your last serious ex?",
    "If you discover you'll die today, what will be your biggest regret?",
    "Do you think you are happier - or sadder - than the average person? Why?",
    "Am I friends with anyone you can't fully endorse? Is there anything you think I should consider about them?",
    "How are we right for each other romantically? Certainly you can think of at least one way we're compatible.",
    "What was your most embarrassing moment that transpired in public? Let's all relive it!",
    "When was the last time you thought you might die? What made you feel that way?",
    "Your Google history has been made public. Which search is the hardest to explain?",
    "What's the worst date you've ever been on? Tell us all the juicy deets.",
    "What are you anxious about? Can we reassure you?",
    "Have you ever done something you're not proud of for money? (Outside of an official job.)",
    "If you had to eat one delectable part of my delicious body, what part would you choose?",
    "What's my greatest physical asset? Don't be shy.",
    "How often do you think about your own death? How, and when, do you suspect it will happen?",
    "Tell us about a time you got more wasted than was advisable.",
    "What's something about your personal hygiene that you could be more rigorous about?",
    "What's something that's definitely not my problem, but somehow always becomes my problem?",
    "If you were to kill me, how would you do it?",
    "What's something you've always done - and only realized as an adult that it was weird?",
    "How would Childhood You describe you now? Would that kid like you?",
    "Do you think you are more or less attractive than the average person? Why?",
    "If we were dying of thirst, how would we ration the last bottle of water between all of us here?",
    "What's an offense you've committed that could get you fired from work?",
    "What would you never, ever want my help with?",
    "How long did it take you to get over your last ex? What did you do to get over it? Are you actually over it?",
    "Tell us about your last breakup talk. Who said what? Anything you wish you'd said?",
    "What's the worst thing you've done in a relationship?",
    "If I killed somebody, would you help me cover it up?",
    "What's the weirdest way you've ever earned money? How much did you get?",
    "If we were to meet for the first time today, would we become friends?",
    "Was your childhood happier than the average person's?",
    "Do you think you're healthier, or more fit, than most people?",
    "What type of person have you always wanted to date, but never had the chance?",
    "Have you ever dated a friend's ex? Ever wanted to?",
    "You and I are dating. What's going to break us up?",
    "What are your insecurities? How do they manifest in your day-to-day life?",
    "Have you ever had a pregnancy scare?",
    "Have you ever been in love? How do you know?",
    "Write me a new dating app bio in three sentences or less.",
    "Will we be friends in ten years?",
    "Is there something that's difficult to talk about amongst any of us here? Should we clear the air right now?",
    "Of the people here, who is overdue for some kind words? Let's offer some good vibes now.",
    "How are we wrong for each other romantically?",
    "What album title describes our relationship? What is our soundtrack?",
    "Tell us about a secret you had to keep from your loved ones.",
    "What did you get in major trouble for doing as a kid, and did you ever learn your lesson?",
    "Our minds have traded bodies. What's the first thing you're going to do in my body?",
    "Describe me in three words.",
    "When was the last time you cried? What happened? Do you need a hug?",
    "How comfortable are we with one another? What things would make us uncomfortable?",
    "Have you ever had a discovery about your parents now that you've grown up?",
    "Do you think I care more or less about my reputation than most people?",
    "What is your worst coping mechanism? Defense mechanism?",
    "Do you think I have a more dominant or more submissive personality? Do you have any examples?",
    "What's the meanest thing you've seen me do?",
    "Do you think you're more prone to addiction than other people? Either way, how do you know?",
    "Have you broken any bones? What happened? Did you hear the crack?",
    "Describe my perfect life partner. Have I been on the right track to find this person?",
    "What's a time when you let a problem go on for too long before you addressed it?",
    "Is there a limit to what you would do for the right amount of money?",
    "When was the last time you spoke to an ex? What was it about? Was there any tension?",
    "Have you ever talked about me behind my back? If yes, what did you say?",
    "Someone who's never met me asks you what I'm like. How do you answer?",
    "If someone offered you $10,000 to never talk to me again, would you?",
    "What's something you think people should never joke about?",
    "If I were a chain restaurant, which one would I be and why?",
    "Tell us about the one that got away.",
    "What's something you're still self-conscious about? Are you working on it?",
    "Assuming you were single, what would it take for you to get back together with your last ex?",
    "When was the last time you lost your cool? What happened? How do you feel about it now?",
    "If you found out I'd been embezzling from work, would you rat me out?",
    "Have I ever told you a secret that you've let slip to a third party?",
    "Describe a time when you really disappointed someone. Did you ever earn back their trust?",
    "Describe a way I've impacted your life - but may not know about.",
    "What is something you're struggling with that we don't know about?",
    "What's a grand gesture you tried to save or repair a relationship?",
    "If I listed you as my job reference, what would you say about me? Would it all be true?",
    "Who's the smartest person here? Give us examples.",
    "Tell us about a time you lied to your parents. Did they ever find out?",
    "Have you ever caught me in a lie? Did you confront me about it? Why or why not?",
    "Help me with my ten-year plan. Describe my ideal job, income, relationship status, and attitude ten years from now.",
    "Tell us about a time you were shot down romantically.",
    "Tell us about a time you shot someone down romantically.",
    "What's your most expensive mistake?",
    "Do you have any scars you want to show us? Pick one and tell us the story behind how you got it.",
    "How many kids is too many kids? How many will you have?",
    "What would we do on our first date? (If asking partners or exes: What did you do on your first date?)",
    "When was the last time you lied to me? What was the lie?",
    "Of the people here, who do you think makes the most money? What makes you think so?",
    "Have you ever pooped yourself as an adult?",
  ];

  questionDeck2 = [
    "Pay me three sincere compliments.",
    "What's the best compliment you've ever been given?",
    "What's something you're proud of that not many people know about?",
    "What's the most common thing people praise or compliment you for?",
    "What bad habit have you kicked?",
    "Who here is the kindest? Tell us why - with lovely examples.",
    "Would you 'take care' of a spider for me? What about a cockroach?",
    "Why do you put up with me?",
    "Tell me your favorite joke. If I laugh, I drink.",
    "What motto would you put on your famliy crest?",
    "Describe a time you accidentally mortified your parents as a child.",
    "If I could help you with one unpleasant task, what would it be?",
    "Fill in the blank. Defend yourself: I don't care if _____ is for kids, I will still love it until I die.",
    "What's the best zinger you've ever come up with on the fly? I know you remember it.",
    "What's the the most courageous thing you've ever accomplished?",
    "Do you always try to be honest with me, or do you tell me 'that haircut looks great'-level white lies to be nice?",
    "What are the farthest lengths you've gone to cheer someone up?",
    "Aside from 'moist', what word can't you stand the sound of?",
    "What is your ideal name for a dog? A cat? Now pick any non-traditional pet and name it.",
    "What song are you most ashamed to admit to me that you love? Reply in song.",
    "Am I better or worse off when I am caffeinated?",
    "With what hilarious story about me do you regale people I do not know?",
    "Name a dream of yours that you've made come true.",
    "What movie or TV character do I most remind you of?",
    "What is your happiest memory from when you were a single-digit-aged child?",
    "What's a situation that is always improved by my presence?",
    "Who would play me in the Oscar-winning film about my life?",
    "When's the exact moment you knew we were on the same wavelength?",
    "If you had synesthesia, what color would I make you feel?",
    "How have I helped you the most?",
    "What's the most considerate present you've ever received? Given?",
    "What's the title of your autobiography? Extra imaginary points if it includes a colon and a subtitle.",
    "What movie or TV quote hits a little too close to home?",
    "If dogs and their owners are supposed to have matching personalities, what type of dog should I get?",
    "Would you give me one of your kidneys?",
    "What's your favorite memory of our relationship?",
    "What snack do you find the most comfort in consuming?",
    "What is something you love about me that other people don't understand at all?",
    "What positive impact do you think you have on other people?",
    "If you could have any body part of mine (for aesthetic, not medical, reasons), what would it be?",
    "If you could plan the perfect night with all of your friends, what would it entail?",
    "What would you entrust me with above anyone else?",
    "What board game are you positive you could destroy us all at?",
    "Describe the dream vacation you haven't gotten to take. Then tell me how you can make it happen in five years or less.",
    "What dish do you slay in the kitchen every time you make it?",
    "What's something I'm self-conscious about that you think I should stop stressing out over?",
    "What's your ultimate Sunday look like? Your ultimate sundae?",
    "What are you rooting for me to achieve?",
    "What author's body of work do you wish you were actually responsible for?",
    "If you could instantly gain any skill, what would it be?",
    "On what topic could you be an expert TV talking head?",
    "If there were no barriers to entry, what job do you think you'd be amazing at?",
    "Out of all of us, whose eyes would you like to see the world through for a day?",
    "Show me the funniest thing on the internet under 30 seconds long. If I laugh, I drink.",
    "We're binging tonight! Pick the show and the snack.",
    "Would you ever see a band in concert that you hated just to make me happy? Have you?",
    "If I were a perfume or cologne, what would my top, heart, and base notes be?",
    "What song reminds you of me whenever you hear it?",
    "Do you ever just let me win?",
    "When do you think you peaked?",
    "What best represents me as a friend: a weighted blanket, a spin class, or a wine tasting?",
    "What's the most kickass you've ever felt?",
    "What's the most fun you've ever had with strangers? Tell us the story.",
    "We're starting a business. What venture would we be most successful at as a pair?",
    "If we formed a gang, what would the name of our posse be?",
    "What do you wish you were as good at as me?",
    "What is something you know you'll accomplish, no matter how many people tell you you can't?",
    "What makes you so much fun?",
    "How many seconds is the ideal hug? Should we all test your hypothesis?",
    "If you could live anyone else's life, whose would it be?",
    "What is the most comforting sound in the world?",
    "If someone did me wrong, would you (a) comfort me, (b) distract me, or (c) get revenge for me?",
    "Describe an act of petty protest you waged at work or school.",
    "What's something that completely changed you when you encountered it for the first time?",
    "What discontinued item would you give anything to bring back?",
    "What's one thing you can start doing to put more beauty back into the world?",
    "Do you ever pity-laugh at my jokes, even if you don't think they're funny?",
    "Would you trust me to pierce your ear, 80's-sleepover style?",
    "I'm going to have permanent art deposited into my skin with needles. Pick a design for me. Bonus points if you draw it.",
    "What smell takes you back to childhood?",
    "You suddenly become wealthy beyond the dreams of avarice. What do you do with the rest of your life?",
    "What's the biggest fear you've overcome?",
    "Do you brag about me to other people? What do you say?",
    "What's the weirdest compliment you've ever gotten?",
    "What would be your cheesy, 20-second, game-showcontestant anecdote?",
    "What's guaranteed to hit you right in the feels?",
    "We're road tripping through the middle of nowhere. Do you have me drive or navigate?",
    "If I couldn't reach an itch, would you do me a solid and scratch it?",
    "If you were a Care Bear, what would be on your belly?",
    "What was your first impression of me? Has it turned out to be the case?",
    "What's the hold music for your brain?",
    "What's the strangest nickname you've ever been given?",
    "You get to travel back in time to warn me about one thing. What would it be?",
    "Liking what piece of pop culture gets someone your automatic stamp of approval?",
    "Of all the things we do together, what is the best thing we do together?",
    "If we were flying somewhere together, who would volunteer to sit in the middle seat?",
    "What did you think you would hate, but ended up loving?",
    "What do you secretly think I'd be amazing at?",
    "Tell me about a disagreement we had - and how we resolved it. Has it made us stronger?",
    "What album have you spun the most times? Be honest. You can consult your music apps for verification.",
    "Who here is most likely to believe in supernatural, occult, or mystical stuff?",
    "What is your greatest style-related regret as an adult? Have you glo'd up since?",
    "What's the most embarassing thing you've had to ask Google?",
    "When was the last time you laughed so hard you cried?",
  ];

  questionDeck3 = [
    "Have you ever broken off plans with me to be with someone else?",
    "Who is in control in our relationship?",
    "Does our relationship bring out the best in you? In me? If not, why?",
    "What's something you resent about me?",
    "Describe three ways to improve my physical appearance and general attractiveness.",
    "Describe a time you lost a little bit of respect for me.",
    "What percentage of the time do you think I'm completely full of shit?",
    "Do you even remotely care what I think of you?",
    "Do you think I'm more or less honest than you are?",
    "What's a fundamental difference between us, and will we ever resolve it?",
    "Where are we, and what are we doing, in ten years? Have we honestly improved each other's lives?",
    "Do you ever put me down to make yourself feel better?",
    "Do you think I'll ever do anything worth being remembered by society?",
    "Have you ever harassed someone online? Do you think they deserved it?",
    "If someone was interested in dating me, what thing about me would you tell them to change their mind?",
    "What problem do I think I'm successfully hiding from everyone, but is actually completely obvious?",
    "What do you wish I'd just shut up about?",
    "What have I ruined for you?",
    "Do you see us as equals?",
    "Do I often seem like I'm being fake?",
    "Do you think I'm good parent material?",
    "What negative thing have I said about you that's haunted you forever?",
    "What ethical boundaries are you happy to cross?",
    "What thing do I love that you absolutely hate?",
    "What one change could I make that would vastly improve who I am as a person?",
    "Am I too picky? Too petty? Too selfish?",
    "Have you ever considered ending our relationship? Why?",
    "Do you ever think I need to cut back on drinking or drugs?",
    "Have I ever done anything you think should have gotten me shitcanned?",
    "What's the most amount of money you would lend me?",
    "What's the most needlessly mean thing you've ever heard me say about someone else?",
    "Are there certain situations with me you avoid on purpose?",
    "What's the most egregious lie you've ever told me?",
    "What personal demon are you in denial of?",
    "What advice do I need but don't want to hear?",
    "Do you think I'm too clingy or demand too much attention?",
    "Do you think I'm continuing to grow, or is this the best I'll ever be as a person?",
    "Do you think I'm capable of doing something you could never forgive me for?",
    "Are you sometimes embarrassed to be seen with me? Why?",
    "Do you think I have overachieved or underachieved?",
    "Name one thing I do that disgusts you.",
    "What do I never seem to understand about you?",
    "What will you never understand about me?",
    "How have I disappointed you?",
    "Have you ever hurt someone on purpose?",
    "Name a time you wished we weren't friends.",
    "Do you ever feel like I'm holding you back?",
    "What do you think I need to just let go of?",
    "Who's someone we know that you wish I was more like and why?",
    "If I was in a relationship with someone you hated, would you tell me?",
    "Is there anything about me that creeps you out?",
    "Do you have any secrets you keep from me and me only?",
    "Have I often struck you as immature or unable to take care of myself?",
    "Would you hire me?",
    "Is there an expiration date on our relationship?",
    "Do you think I sometimes takes advantage of other people?",
    "What do I think I'm great at, but am actually terrible at?",
    "What's the most serious crime you've ever committed?",
    "What's the worst thought you've ever had that you've never shared with anyone?",
    "Have you ever been genuinely scared of me?",
    "What is (or would be) the worst thing about having me as a travel companion?",
    "Do you think I'm a bully?",
    "What's the bitchiest thing you've ever said about me behind my back?",
    "What's the most selfish thing you've ever done?",
    "What's an offensive opinion you will never let go of?",
    "Name a time you could have helped someone, but didn't bother.",
    "What's stupidest thing you've ever heard me say?",
    "Do you think you're better than me?",
    "If you do something you know is wrong, but don't get caught, do you keep doing it?",
    "Have you ever stolen anything from me?",
    "If I died tomorrow, what regrets would you have about our relationship?",
    "What's the longest period of time you could spend with me before never wanting to see me again?",
    "What's the weirdest thing about me?",
    "Have you ever knowingly let me embarrass myself, even if you could have stopped it?",
    "Do you sometimes lie about being busy if you don't want to deal with me?",
    "Do you ever warn people about me before they meet me?",
    "Have you ever ghosted someone you were close with?",
    "Would you trust me alone with your kids for more than a couple hours?",
    "Do you ever have to fake empathy?",
    "What's the most annoying thing I do without realizing it?",
    "What am I the most ignorant about?",
    "What's something you know would make you a better person, but you just don't want to do it?",
    "Is this the best I've looked since you've known me?",
    "Do you ever think I stir up drama because I enjoy it?",
    "Have you ever stabbed someone in the back or actively plotted against them?",
    "What's the worst thing you've ever done to an animal?",
    "How have I changed for the worse since we've met?",
    "What's the most terrible thing you've ever done for money?",
    "In what ways have you used me?",
    "What's the most unreasonable thing you've ever completely lost your shit over?",
    "How have you dishonored your parents?",
    "Have you ever had to apologize to someone for my behavior?",
    "Have you ever intentionally scammed someone or misled them for personal gain?",
    "Name a time you thought I was weak.",
    "When have you let your pride get in the way of doing the right thing?",
    "If someone important to you said they'd stop seeing you unless you stopped seeing me, would you?",
    "When was the last time you were out of control?",
    "Have you ever forced someone to do something against their will?",
    "Have you ever pretended to be someone else on the internet?",
    "Have you ever lied on a resume?",
    "What's the angriest you've ever been at me?",
    "Would your life be any worse if we had never met?",
    "What have you done while intoxicated that you wish you could take back?",
    "If we lived across the country from each other, do you think we'd lose touch?",
  ];
}
